#!/usr/bin/env bash
# =============================================================================
# paramminer.sh — Param Miner is a Burp Suite extension, NOT a CLI tool.
# This module does not fabricate a command-line invocation for it. Instead it
# ranks the most interesting candidate URLs and writes them to a file the
# user imports into Burp's target scope for manual Param Miner analysis.
#
# If your environment has a genuine headless/CLI integration for Param Miner
# (uncommon), set PARAMMINER_CLI in config.conf and it will be invoked here.
# =============================================================================

# prepare_paramminer_targets CANDIDATES_JSONL WCVS_STDOUT NUCLEI_JSONL OUT_FILE
# Ranks by: presence of cache indicators, parameter count, WCVS/Nuclei hits.
prepare_paramminer_targets() {
    local cache_jsonl="$1" wcvs_out="$2" nuclei_jsonl="$3" out="$4"
    ensure_dirs "$(dirname "$out")"

    if [[ "${USE_PARAMMINER:-true}" != "true" ]]; then
        log_info "Param Miner target prep skipped (--skip-paramminer)"
        : > "$out"
        return 0
    fi

    local scored_tmp; scored_tmp=$(mktemp)
    : > "$scored_tmp"

    if [[ -s "$cache_jsonl" ]]; then
        while IFS= read -r line; do
            local url score=0
            url=$(echo "$line" | grep -oE '"url":"[^"]*"' | head -1 | sed -E 's/"url":"([^"]*)"/\1/')
            [[ -z "$url" ]] && continue

            # +2 for any cache header presence signal in the line
            echo "$line" | grep -Eiq '"x_cache":"[^"]+"|"cf_cache_status":"[^"]+"' && score=$((score+2))
            # +1 per param
            local pcount; pcount=$(grep -o '[?&]' <<< "$url" | wc -l | tr -d ' ')
            score=$((score + pcount))
            # +3 if WCVS mentions this URL
            [[ -f "$wcvs_out" ]] && grep -qF "$url" "$wcvs_out" 2>/dev/null && score=$((score+3))
            # +3 if Nuclei flagged this URL
            [[ -f "$nuclei_jsonl" ]] && grep -qF "$url" "$nuclei_jsonl" 2>/dev/null && score=$((score+3))

            printf '%d\t%s\n' "$score" "$url" >> "$scored_tmp"
        done < "$cache_jsonl"
    fi

    sort -t $'\t' -k1,1nr -u "$scored_tmp" | awk -F'\t' '!seen[$2]++' > "$out.ranked"
    {
        echo "# Param Miner manual analysis targets — ranked (highest priority first)"
        echo "# Generated by CacheHunter. Import into Burp Suite's target scope, then"
        echo "# run Param Miner's 'Guess GET/POST/headers/cookie params' + 'Guess"
        echo "# cache-related params' against these. See README.md section"
        echo "# 'Param Miner workflow' for the manual steps."
        echo "#"
        echo "# score<TAB>url"
        cat "$out.ranked"
    } > "$out"
    rm -f "$scored_tmp" "$out.ranked"

    if [[ -n "${PARAMMINER_CLI:-}" ]] && command -v "$PARAMMINER_CLI" >/dev/null 2>&1; then
        log_info "PARAMMINER_CLI configured — invoking $PARAMMINER_CLI (user-provided integration)"
        "$PARAMMINER_CLI" --input "$out" --output "$(dirname "$out")/paramminer-cli-results.txt" \
            2>>"$LOG_FILE" || log_warn "PARAMMINER_CLI exited non-zero — see log"
    else
        log_info "Param Miner has no CLI in this environment — targets prepared for manual Burp import"
    fi

    log_ok "$(grep -cv '^#' "$out" 2>/dev/null || echo 0) target(s) ranked for Param Miner"
}
